import AppProviders from "@/components/providers/AppProvider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SiteFooter } from "@/components/shared/footer";
import { SiteHeader } from "@/components/shared/header";
import type { Metadata } from "next";
import { Fraunces, Sora } from "next/font/google";
import "./globals.css";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${sora.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProviders>
            <SiteHeader />
            {children}
            <SiteFooter />
          </AppProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
